import {Store,Row,uid,day} from './store';
export const defaultSettings={lineId:'',taxId:'',branch:'สำนักงานใหญ่',vatMode:'none',logo:'',signature:'',logoSize:'medium',receiptPaper:'80mm',jobPaper:'80mm',printOrientation:'portrait',printMargin:3,printFontSize:11,printRollHeight:200,footer:'ขอบคุณที่ใช้บริการ',bank:'',accountNo:'',accountName:'',promptpay:'',paymentNote:'กรุณาตรวจสอบชื่อผู้รับเงินก่อนโอน',showPaymentQr:true,showLogo:true,autoPrint:false,costSource:'job',showCosts:true,enableAttendance:false,enablePayroll:false,defaultWarranty:'30 วัน',lineOaUrl:''};
export function normalizeStore(s:Store):Store{return {...s,settings:{...defaultSettings,...s.settings},prices:s.prices??[],attendance:s.attendance??[],payroll:s.payroll??[]};}
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function calculateBill(amount:number,discount:number,mode:string){const after=round(Math.max(0,amount-discount));const vat=mode==='excluded'?round(after*.07):mode==='included'?round(after*7/107):0;return {subtotal:round(amount),discount:round(discount),net:mode==='included'?round(after-vat):after,vat,total:mode==='excluded'?round(after+vat):after,vatMode:mode};}
export function repairIdentity(r:Row){return [r.brand,r.model,r.work,r.grade].map(x=>String(x??'').trim().toLowerCase()).join('|');}
export function mergePrices(old:Row[],incoming:Row[]){const result=old.map(r=>({...r}));for(const row of incoming){if(!row.brand||!row.model||!row.work||!Number.isFinite(row.price)||row.price<0||!Number.isFinite(row.cost)||row.cost<0)throw Error('กรุณาตรวจยี่ห้อ รุ่น งานซ่อม ต้นทุน และราคาซ่อมในทุกแถว');const i=result.findIndex(r=>repairIdentity(r)===repairIdentity(row));if(i>=0)result[i]={...result[i],...row,id:result[i].id};else result.push({...row,id:uid(),date:day()});}return result;}
export function recordQuickWork(s:Store,d:{issue:string;price:number;cost:number;customer:string;warranty:string;method:string;technician:string}){if(!d.issue.trim()||!Number.isFinite(d.price)||d.price<0||!Number.isFinite(d.cost)||d.cost<0)throw Error('กรอกงาน ราคา และต้นทุนให้ถูกต้อง');const n=structuredClone(s),id=uid();const bill=calculateBill(d.price,0,n.settings.vatMode??'none');const code='Q-'+day().replaceAll('-','')+'-'+id.slice(0,6).toUpperCase();const r={id,code,date:day(),customer:d.customer.trim()||'ลูกค้าหน้าร้าน',phone:'',brand:'',model:'บริการหน้าร้าน',issue:d.issue,cost:d.cost,price:bill.total,deposit:0,due:day(),technician:d.technician,method:d.method,warranty:d.warranty,status:'ส่งคืนแล้ว',settled:true,quick:true,bill,shop:structuredClone(n.settings),timeline:[{status:'ส่งคืนแล้ว',date:new Date().toISOString()}]};n.repairs.unshift(r);if(bill.total>0)n.finance.unshift({id:uid(),reference:id,date:day(),type:'รายรับ',description:'งานด่วน '+code+' · '+d.issue,amount:bill.total,category:'งานซ่อม',method:d.method});if(d.cost>0&&n.settings.costSource!=='expense')n.finance.unshift({id:uid(),reference:id,date:day(),type:'รายจ่าย',description:'ต้นทุนงานด่วน '+code,amount:d.cost,category:'ต้นทุนซ่อม',method:d.method});return {store:n,repair:r,receipt:{...r,...bill,kind:'ใบเสร็จงานด่วน',items:[{name:d.issue,qty:1,price:d.price}]}};}
export function crc16(s:string){let crc=0xffff;for(let i=0;i<s.length;i++){crc^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=crc&0x8000?(crc<<1)^0x1021:crc<<1;crc&=0xffff;}return crc.toString(16).toUpperCase().padStart(4,'0');}
export function promptpayPayload(id:string,amount:number){const digits=id.replace(/\D/g,'');let target='';if(/^0\d{9}$/.test(digits))target='01130066'+digits.slice(1);else if(/^\d{13}$/.test(digits))target='0213'+digits;else throw Error('พร้อมเพย์ต้องเป็นเบอร์โทร 10 หลักหรือเลขประจำตัว 13 หลัก');if(!Number.isFinite(amount)||amount<=0)throw Error('ยอดเงินไม่ถูกต้อง');const merchant='0016A000000677010111'+target;const a=amount.toFixed(2);const base='00020101021229'+String(merchant.length).padStart(2,'0')+merchant+'5802TH530376454'+String(a.length).padStart(2,'0')+a+'6304';return base+crc16(base);}
