import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const properties={},files={},cache=new Map(),sent=[];let next=0;
const makeFile=(name,text)=>{const id=String(++next);files[id]={name,text};return {getId:()=>id}};
const context={console,Date,JSON,Math,Number,String,Array,Object,isFinite,encodeURIComponent,MimeType:{PLAIN_TEXT:'text/plain'},Session:{getActiveUser:()=>({getEmail:()=> 'slam.mobay96000@gmail.com'})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k],setProperties:p=>Object.assign(properties,p)})},DriveApp:{createFolder:()=>({getId:()=> 'folder',createFile:makeFile}),getFolderById:()=>({createFile:makeFile}),getFileById:id=>({getBlob:()=>({getDataAsString:()=>files[id].text}),setContent:t=>files[id].text=t})},CacheService:{getScriptCache:()=>({get:k=>{const v=cache.get(k);return v&&v.expires>Date.now()?v.value:null},put:(k,value,s)=>cache.set(k,{value,expires:Date.now()+s*1000}),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:m=>sent.push(m)},Utilities:{getUuid:()=>crypto.randomUUID(),Charset:{UTF_8:'UTF-8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()]}};
vm.createContext(context);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8'),context);context.setupMobileHub();
const call=(path,method='GET',body={},session='')=>JSON.parse(JSON.stringify(context.api({path,method,body,session})));
assert.equal(call('/api/store').status,401);
assert.equal(call('/api/auth','POST',{action:'owner-code'}).status,200);
const code=sent.at(-1).body.match(/: (\d{6})/)[1];const owner=call('/api/auth','POST',{action:'owner-verify',code}).body.session;assert(owner);
assert.equal(call('/api/auth','POST',{action:'owner-verify',code}).status,401);
assert.equal(call('/api/admin/access','GET',{},owner).body.ownerEmail,'slam.mobay96000@gmail.com');
let state=call('/api/store','GET',{},owner).body;
state.data.customers.push({id:'test-customer',name:'ทดสอบ',phone:'0000000000'});
assert.equal(call('/api/store','PUT',state,owner).status,200);assert.equal(call('/api/store','PUT',state,owner).status,409);
const email='staff@example.test',passwordProof='a'.repeat(64);
assert.equal(call('/api/auth','POST',{action:'register',email,name:'ทดสอบพนักงาน',phone:'0000000000',passwordProof,role:'owner',status:'approved'}).status,200);
const auth=JSON.parse(files[properties.AUTH_FILE_ID].text),staff=auth.users.find(u=>u.email===email);assert.equal(staff.role,'staff');assert.equal(staff.status,'pending');
assert.equal(call('/api/auth','POST',{action:'login',email,passwordProof}).status,403);
const verifyMail=sent.find(m=>m.to===email&&m.subject.includes('ยืนยัน'));const token=new URL(verifyMail.body.match(/https:\/\/\S+/)[0]).searchParams.get('token');
assert.equal(call('/api/auth','POST',{action:'verify',token}).status,200);assert.equal(call('/api/auth','POST',{action:'verify',token}).status,400);
assert.equal(call('/api/auth','POST',{action:'login',email,passwordProof}).status,403);
assert.equal(call('/api/admin/access','POST',{action:'decision',id:staff.id,status:'approved'},owner).status,200);
const staffSession=call('/api/auth','POST',{action:'login',email,passwordProof}).body.session;assert(staffSession);
assert.equal(call('/api/admin/access','GET',{},staffSession).status,403);
state=call('/api/store','GET',{},staffSession).body;state.data.settings.phone='should-deny';assert.equal(call('/api/store','PUT',state,staffSession).status,403);
state=call('/api/store','GET',{},staffSession).body;state.data.customers.push({id:'staff-test',name:'ทดสอบบันทึกจากพนักงาน'});assert.equal(call('/api/store','PUT',state,staffSession).status,200);
assert.equal(call('/api/admin/access','POST',{action:'decision',id:staff.id,status:'disabled'},owner).status,200);assert.equal(call('/api/store','GET',{},staffSession).status,401);
assert.equal(call('/api/auth','POST',{action:'forgot',email}).status,200);
const resetToken=new URL(sent.at(-1).body.match(/https:\/\/\S+/)[0]).searchParams.get('token');assert.equal(call('/api/auth','POST',{action:'reset-password',token:resetToken,email,passwordProof:'b'.repeat(64)}).status,200);assert.equal(call('/api/auth','POST',{action:'reset-password',token:resetToken,email,passwordProof:'b'.repeat(64)}).status,400);
assert.equal(call('/api/auth','POST',{action:'owner-password',passwordProof:'c'.repeat(64)},owner).status,200);
state=call('/api/store','GET',{},owner).body;assert.equal(call('/api/admin/reset','POST',{confirmation:'ล้างข้อมูลร้านทั้งหมด',revision:state.revision,passwordProof:'c'.repeat(64)},owner).status,200);
assert.equal(call('/api/store','GET',{},owner).body.data.customers.length,0);assert(Object.values(files).some(f=>f.name.startsWith('backup-before-reset-')));
console.log('PASS: persistence, revision conflicts, owner OTP, registration, email verification, approval, staff permissions, session revocation, password reset, and backed-up system reset');
