import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const properties={},files={},cache=new Map(),sent=[];let next=0;
const makeFile=(name,text)=>{const id=String(++next);files[id]={name,text};return {getId:()=>id}};
const context={console,Date,JSON,Math,Number,String,Array,Object,isFinite,encodeURIComponent,MimeType:{PLAIN_TEXT:'text/plain'},Session:{getActiveUser:()=>({getEmail:()=> 'slam.mobay96000@gmail.com'})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k],setProperties:p=>Object.assign(properties,p),setProperty:(k,v)=>properties[k]=v})},DriveApp:{createFolder:()=>({getId:()=> 'folder',createFile:makeFile}),getFolderById:()=>({createFile:makeFile}),getFileById:id=>({getBlob:()=>({getDataAsString:()=>files[id].text}),setContent:t=>files[id].text=t})},CacheService:{getScriptCache:()=>({get:k=>{const v=cache.get(k);return v&&v.expires>Date.now()?v.value:null},put:(k,value,s)=>cache.set(k,{value,expires:Date.now()+s*1000}),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock:()=>{},releaseLock:()=>{}})},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:m=>sent.push(m)},Utilities:{getUuid:()=>crypto.randomUUID(),Charset:{UTF_8:'UTF-8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()]}};
vm.createContext(context);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8'),context);context.setupMobileHub();
const call=(path,method='GET',body={},session='')=>JSON.parse(JSON.stringify(context.api({path,method,body,session})));
const confirmed=(path,method,body,session)=>{
 for(const k of cache.keys())if(k.startsWith('limit:'))cache.delete(k);
 const challenge=call('/api/security','POST',{target:{path,method,body}},session);if(challenge.status!==200)return challenge;
 const mails=sent.slice(-2),code=sent.findLast(m=>m.to===challenge.body.email&&m.subject.includes('เปลี่ยนแปลง')).body.match(/รหัสยืนยัน: (\d{6})/)[1];
 const newEmailCode=challenge.body.newEmail?mails.find(m=>m.to===challenge.body.newEmail).body.match(/ใหม่: (\d{6})/)[1]:'';
 return call(path,method,{...body,changeId:challenge.body.changeId,changeCode:code,newEmailCode},session);
};
assert.equal(call('/api/store').status,401);
assert.equal(call('/api/auth','POST',{action:'owner-code'}).status,200);
const code=sent.at(-1).body.match(/: (\d{6})/)[1];const owner=call('/api/auth','POST',{action:'owner-verify',code}).body.session;assert(owner);
assert.equal(call('/api/auth','POST',{action:'owner-verify',code}).status,401);
assert.equal(call('/api/admin/access','GET',{},owner).body.ownerEmail,'niasae.purong@gmail.com');
let state=call('/api/store','GET',{},owner).body;
state.data.customers.push({id:'test-customer',name:'ทดสอบ',phone:'0000000000'});
const mailsBeforeStoreSave=sent.length;
assert.equal(call('/api/store','PUT',state,owner).status,200);assert.equal(call('/api/store','PUT',state,owner).status,409);
assert.equal(sent.length,mailsBeforeStoreSave,'Routine saves must not send verification email');
const email='staff@example.test',passwordProof='a'.repeat(64);
assert.equal(call('/api/auth','POST',{action:'register',email,name:'ทดสอบพนักงาน',phone:'0000000000',passwordProof,role:'owner',status:'approved'}).status,200);
const auth=JSON.parse(files[properties.AUTH_FILE_ID].text),staff=auth.users.find(u=>u.email===email);assert.equal(staff.role,'staff');assert.equal(staff.status,'pending');
assert.equal(call('/api/auth','POST',{action:'login',email,passwordProof}).status,403);
const verifyMail=sent.find(m=>m.to===email&&m.subject.includes('ยืนยัน'));const token=new URL(verifyMail.body.match(/https:\/\/\S+/)[0]).searchParams.get('token');
assert.equal(call('/api/auth','POST',{action:'verify',token}).status,200);assert.equal(call('/api/auth','POST',{action:'verify',token}).status,400);
assert.equal(call('/api/auth','POST',{action:'login',email,passwordProof}).status,403);
assert.equal(confirmed('/api/admin/access','POST',{action:'decision',id:staff.id,status:'approved'},owner).status,200);
const staffSession=call('/api/auth','POST',{action:'login',email,passwordProof}).body.session;assert(staffSession);
assert.equal(call('/api/admin/access','GET',{},staffSession).status,403);
state=call('/api/store','GET',{},staffSession).body;state.data.settings.phone='should-deny';assert.equal(call('/api/store','PUT',state,staffSession).status,403);
state=call('/api/store','GET',{},staffSession).body;state.data.customers.push({id:'staff-test',name:'ทดสอบบันทึกจากพนักงาน'});assert.equal(call('/api/store','PUT',state,staffSession).status,200);
assert.equal(confirmed('/api/admin/access','POST',{action:'edit-user',id:staff.id,name:'แก้ไข',phone:'081-1234567'},staffSession).status,403);
assert.equal(confirmed('/api/admin/access','POST',{action:'edit-user',id:staff.id,name:'แก้ไข',phone:'123'},owner).status,400);
assert.equal(confirmed('/api/admin/access','POST',{action:'edit-user',id:staff.id,name:'แก้ไข',phone:'0811234567'},owner).status,200);
assert.equal(call('/api/admin/access','GET',{},owner).body.users.find(u=>u.id===staff.id).phone,'081-1234567');
const ownerId=call('/api/admin/access','GET',{},owner).body.users.find(u=>u.role==='owner').id;
assert.equal(confirmed('/api/admin/access','POST',{action:'delete-user',id:ownerId,confirmation:'ลบคำขอพนักงาน'},owner).status,404);
assert.equal(confirmed('/api/admin/access','POST',{action:'delete-user',id:staff.id},owner).status,400);
assert.equal(confirmed('/api/admin/access','POST',{action:'delete-user',id:staff.id,confirmation:'ลบคำขอพนักงาน'},owner).status,200);
assert.equal(call('/api/store','GET',{},staffSession).status,401);
assert.equal(confirmed('/api/admin/access','POST',{action:'decision',id:staff.id,status:'approved'},owner).status,400);
assert.equal(confirmed('/api/admin/access','POST',{action:'restore-user',id:staff.id},owner).status,200);
assert.equal(call('/api/auth','POST',{action:'login',email,passwordProof}).status,403);
assert.equal(confirmed('/api/admin/access','POST',{action:'decision',id:staff.id,status:'approved'},owner).status,200);
assert.equal(confirmed('/api/admin/access','POST',{action:'decision',id:staff.id,status:'disabled'},owner).status,200);assert.equal(call('/api/store','GET',{},staffSession).status,401);
assert.equal(call('/api/auth','POST',{action:'forgot',email}).status,200);
const resetToken=new URL(sent.at(-1).body.match(/https:\/\/\S+/)[0]).searchParams.get('token');assert.equal(call('/api/auth','POST',{action:'reset-password',token:resetToken,email,passwordProof:'b'.repeat(64)}).status,200);assert.equal(call('/api/auth','POST',{action:'reset-password',token:resetToken,email,passwordProof:'b'.repeat(64)}).status,400);
assert.equal(confirmed('/api/auth','POST',{action:'owner-password',passwordProof:'c'.repeat(64)},owner).status,200);
state=call('/api/store','GET',{},owner).body;assert.equal(confirmed('/api/admin/reset','POST',{confirmation:'ล้างข้อมูลร้านทั้งหมด',revision:state.revision,passwordProof:'c'.repeat(64)},owner).status,200);
assert.equal(call('/api/store','GET',{},owner).body.data.customers.length,0);assert(Object.values(files).some(f=>f.name.startsWith('backup-before-reset-')));
console.log('PASS: persistence, revision conflicts, owner OTP, registration, email verification, approval, staff permissions, session revocation, password reset, and backed-up system reset');

// Regular business updates bypass OTP, but authentication, access and account changes remain protected.
state=call('/api/store','GET',{},owner).body;
const sentBeforeRoutineUpdate=sent.length;
assert.equal(call('/api/store','PUT',state,owner).status,200);
assert.equal(sent.length,sentBeforeRoutineUpdate,'Normal store updates must not send codes');
assert.equal(call('/api/security','POST',{target:{path:'/api/store',method:'PUT',body:state}},owner).status,400);

const target={path:'/api/auth',method:'POST',body:{action:'owner-password',passwordProof:'c'.repeat(64)}};
assert.equal(call('/api/auth','POST',target.body,owner).status,428);
let issue=call('/api/security','POST',{target},owner);let otp=sent.at(-1).body.match(/รหัสยืนยัน: (\d{6})/)[1];
let payload={...target.body,changeId:issue.body.changeId,changeCode:otp};
assert.equal(call('/api/auth','POST',{...payload,passwordProof:'d'.repeat(64)},owner).status,428);
assert.equal(call('/api/auth','POST',{...payload,changeCode:'wrong'},owner).status,428);
assert.equal(call('/api/auth','POST',payload,owner).status,200);
assert.equal(call('/api/auth','POST',payload,owner).status,428);
issue=call('/api/security','POST',{target},owner);otp=sent.at(-1).body.match(/รหัสยืนยัน: (\d{6})/)[1];
cache.get('change:'+context.hash_(issue.body.changeId)).expires=Date.now()-1;
assert.equal(call('/api/auth','POST',{...target.body,changeId:issue.body.changeId,changeCode:otp},owner).status,428);
assert.equal(call('/api/admin/owner','POST',{email:'new-owner@example.test'},owner).status,428);
assert.equal(confirmed('/api/admin/owner','POST',{email:'new-owner@example.test'},owner).status,200);
assert.equal(call('/api/store','GET',{},owner).status,401);
assert.equal(call('/api/auth').body.ownerEmail,'new-owner@example.test');
assert.equal(call('/api/auth','POST',{action:'login',email:'niasae.purong@gmail.com',passwordProof:'c'.repeat(64)}).status,401);
const accounts=JSON.parse(files[properties.AUTH_FILE_ID].text).users;assert.equal(accounts.filter(u=>u.role==='owner').length,1);assert.equal(accounts.find(u=>u.role==='owner').email,'new-owner@example.test');
assert.equal(properties.AUTH_FILE_ID,'1');assert.equal(properties.STORE_FILE_ID,'2');
console.log('PASS: routine no-OTP save, account-only OTP, tamper protection, expiry, replay protection, and owner transfer');

// Existing storage owner is retired, without touching stored business data or granting a pre-registered password.
const businessBefore=files[properties.STORE_FILE_ID].text;
const legacy={users:[{id:'legacy-owner',email:'slam.mobay96000@gmail.com',role:'owner',status:'approved',verified:1,passwordHash:'old'},{id:'preregistered',email:'niasae.purong@gmail.com',role:'staff',status:'pending',verified:0,passwordHash:'attacker-proof'}],sessions:{[context.hash_('legacy-session')]:{userId:'legacy-owner',expires:Date.now()+60000}},tokens:{},mails:[]};
files[properties.AUTH_FILE_ID].text=JSON.stringify(legacy);delete properties.OWNERSHIP_V2;delete properties.OWNER_EMAIL;
assert.equal(call('/api/store','GET',{},'legacy-session').status,401);
const migrated=JSON.parse(files[properties.AUTH_FILE_ID].text);assert.equal(migrated.users.filter(u=>u.role==='owner').length,1);assert.equal(migrated.users.find(u=>u.role==='owner').passwordHash,'');assert.equal(migrated.users.find(u=>u.id==='legacy-owner').role,'retired-owner');assert.equal(files[properties.STORE_FILE_ID].text,businessBefore);
console.log('PASS: legacy migration preserves business data, revokes old owner and clears pre-existing credentials');
