'use client';
import PhoneInput from './PhoneInput';
import {validPhone} from '@/lib/phone';
import {useEffect,useState} from 'react';
import {Smartphone,Mail,LockKeyhole,ArrowRight,CheckCircle2,Home,RefreshCw,ArrowLeft} from 'lucide-react';
export type LoginUser={id:string;email:string;name:string;role:'owner'|'staff';platform?:boolean};
const boot=(window as any).MOBILEHUB_BOOT??{};
export function AuthGate({children}:{children:(u:LoginUser,logout:()=>Promise<void>)=>React.ReactNode}){
 const [user,setUser]=useState<LoginUser|null>(null),[loading,setLoading]=useState(true);
 async function load(){try{const v=await (await fetch('/api/auth')).json();setUser(v.user??null)}finally{setLoading(false)}}
 useEffect(()=>{load();window.addEventListener('mobilehub-auth',load);return()=>window.removeEventListener('mobilehub-auth',load)},[]);
 async function logout(){await fetch('/api/auth',{method:'POST',body:JSON.stringify({action:'logout'})});setUser(null)}
 if(loading)return <div className="authloading"><Smartphone/><p>กำลังตรวจสอบบัญชี…</p></div>;
 return user?children(user,logout):<AuthScreen/>;
}
export default function AuthScreen(){
 const [mode,setMode]=useState(boot.mode??'login'),[email,setEmail]=useState(boot.email??''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const titles:any={login:'เข้าสู่ระบบ',register:'สมัครพนักงาน',forgot:'ลืมรหัสผ่าน',verify:'ยืนยันอีเมล',reset:'ตั้งรหัสผ่านใหม่',owner:'เจ้าของร้าน · เข้าทางอีเมล'};
 function change(m:string){setMode(m);setError('');setMessage('');setPassword('');setConfirm('')}
 async function call(body:any){setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw Error(v.error);if(v.user){window.dispatchEvent(new Event('mobilehub-auth'));return}setMessage(v.message??'ดำเนินการสำเร็จ')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function submit(e:React.FormEvent){e.preventDefault();if(mode==='register'&&!validPhone(phone,true)){setError('กรุณากรอกเบอร์โทรให้ครบ 10 หลัก');return}if(['register','reset'].includes(mode)&&password!==confirm){setError('รหัสผ่านทั้งสองช่องไม่ตรงกัน');return}call({action:mode==='owner'?'owner-verify':mode==='reset'?'reset-password':mode,email,name,phone,password,code,token:boot.token})}
 return <div className="authpage"><div className="authnav"><a className="authbrand" href="#" onClick={()=>change('login')}><Smartphone/><span>สลาม โมบาย<small>MobileHub · ระบบร้านมือถือครบวงจร</small></span></a><div><button className="iconbtn" aria-label="หน้าหลัก" onClick={()=>change('login')}><Home/></button><button className="iconbtn" aria-label="รีเฟรช" onClick={()=>window.dispatchEvent(new Event('mobilehub-auth'))}><RefreshCw/></button><button className="iconbtn" aria-label="ย้อนกลับ" onClick={()=>change('login')}><ArrowLeft/></button></div></div><main className="authlayout"><section className="authintro"><span className="eyebrow">SLAM MOBILE / TEAM ACCESS</span><h1>ร้านของคุณ<br/>พร้อมทำงาน<br/><em>เป็นทีมเดียวกัน</em></h1><p>ขาย ซ่อม สต๊อก และดูแลงานของร้าน<br/>จากมือถือ แท็บเล็ต หรือคอมพิวเตอร์</p><div className="authfeature"><CheckCircle2 size={17}/> พนักงานเข้าใช้หลังเจ้าของร้านอนุมัติ</div><div className="authfeature"><CheckCircle2 size={17}/> บันทึกข้อมูลร่วมกันในบัญชี Google ของร้าน</div><div className="authillustration"><Smartphone size={98}/></div></section><section className="authcard"><div className="authmark"><LockKeyhole size={28}/></div><h2>{titles[mode]??titles.login}</h2><p>{mode==='owner'?'ส่งรหัสยืนยันไปยัง slam.mobay96000@gmail.com รหัสใช้ได้ 10 นาที':mode==='register'?'ส่งคำขอให้เจ้าของร้าน และรับลิงก์ยืนยันทางอีเมล':'ยินดีต้อนรับสู่ระบบร้านสลาม โมบาย'}</p>{mode==='login'&&<div className="authtabs"><button className="selected">เข้าสู่ระบบ</button><button onClick={()=>change('register')}>สมัครพนักงาน</button></div>}
 <form onSubmit={submit}>{mode==='register'&&<><label>ชื่อ–นามสกุล<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>เบอร์โทร<PhoneInput required value={phone} onChange={setPhone}/></label></>}{!['owner','verify'].includes(mode)&&<label>อีเมล<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{['login','register','reset'].includes(mode)&&<label>รหัสผ่าน<input type="password" required minLength={mode==='login'?1:10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{['register','reset'].includes(mode)&&<label>ยืนยันรหัสผ่าน<input type="password" required minLength={10} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}{mode==='owner'&&<><button className="secondary full" type="button" disabled={busy} onClick={()=>call({action:'owner-code'})}><Mail size={17}/> ส่งรหัสเข้าอีเมลเจ้าของร้าน</button><label style={{marginTop:20}}>รหัสยืนยัน 6 หลัก<input required inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label></>}{mode==='login'&&<button type="button" className="textbtn forgotlink" onClick={()=>change('forgot')}>ลืมรหัสผ่าน?</button>}{error&&<div className="autherror" role="alert">{error}</div>}{message&&<div className="authsuccess" role="status">{message}</div>}<button className="primary full" disabled={busy}>{busy?'กำลังดำเนินการ…':mode==='register'?'ส่งคำขอสมัครพนักงาน':mode==='owner'||mode==='login'?'เข้าสู่ระบบ':mode==='forgot'?'ส่งลิงก์รีเซ็ตรหัสผ่าน':mode==='verify'?'ยืนยันอีเมลของฉัน':'บันทึกรหัสผ่านใหม่'}<ArrowRight size={18}/></button></form>
 {mode==='login'&&<button className="textbtn full" style={{marginTop:20}} onClick={()=>change('owner')}>เจ้าของร้าน · เข้าด้วยรหัสทางอีเมล</button>}{mode!=='login'&&<button className="textbtn full" style={{marginTop:20}} onClick={()=>change('login')}>กลับหน้าเข้าสู่ระบบ</button>}{mode==='register'&&<div className="authnote"><b>คำขอส่งถึง</b><span>slam.mobay96000@gmail.com</span><small>ต้องยืนยันอีเมลและได้รับอนุมัติก่อนเข้าใช้ข้อมูลร้าน</small></div>}</section></main><footer className="authfooter">สลาม โมบาย · MobileHub</footer></div>
}
