'use client';
import {useEffect,useRef,useState} from 'react';
export type CardCustomer={nationalId:string;name:string;birthDate:string;address:string};
export function validNationalId(value:string){return /^\d{13}$/.test(value)&&(11-value.slice(0,12).split('').reduce((sum,n,i)=>sum+Number(n)*(13-i),0)%11)%10===Number(value[12])}
export default function CardReader({onRead,disabled=false}:{onRead:(customer:CardCustomer)=>void;disabled?:boolean}){
 const [message,setMessage]=useState(''),[waiting,setWaiting]=useState(false);const cleanup=useRef<()=>void>(()=>{});useEffect(()=>()=>cleanup.current(),[]);
 function connect(){cleanup.current();const bytes=crypto.getRandomValues(new Uint8Array(16)),nonce=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');const popup=window.open('http://127.0.0.1:8765/connect#'+new URLSearchParams({origin:location.origin,nonce}),'_blank','width=620,height=760');if(!popup){setMessage('เบราว์เซอร์ปิดกั้นหน้าต่าง กรุณาอนุญาตป๊อปอัปสำหรับระบบร้าน');return}setWaiting(true);setMessage('เปิดโปรแกรมเชื่อมต่อบนคอมเครื่องนี้ แล้วกดเริ่มอ่านและเสียบบัตรในหน้าต่างที่เปิด');
 let timer:ReturnType<typeof setTimeout>;function stop(){window.removeEventListener('message',receive);clearTimeout(timer);setWaiting(false)}
 function receive(event:MessageEvent){if(event.source!==popup||event.origin!=='http://127.0.0.1:8765'||event.data?.type!=='slam-card-data'||event.data?.nonce!==nonce)return;const c=event.data.data;if(!c||!validNationalId(c.nationalId??'')||typeof c.name!=='string'||!c.name.trim()||c.name.length>150||typeof c.address!=='string'||c.address.length>600||typeof c.birthDate!=='string'||(c.birthDate&&!/^\d{4}-\d{2}-\d{2}$/.test(c.birthDate))){stop();setMessage('ข้อมูลบัตรไม่ถูกต้อง กรุณาอ่านใหม่');return}stop();onRead(c);setMessage('เติมข้อมูลจากบัตรแล้ว กรุณาตรวจและกรอกเบอร์โทรก่อนบันทึก');popup.close()}
 window.addEventListener('message',receive);timer=setTimeout(()=>{stop();setMessage('หมดเวลารอ กรุณาเปิดโปรแกรมเชื่อมต่อและกดอ่านบัตรอีกครั้ง')},120000);cleanup.current=stop;
 }
 return <section className="cardreader wide"><h3>อ่านข้อมูลจากบัตรประชาชน</h3><p className="hint">สำหรับเครื่องอ่าน USB บน Windows ที่ติดตั้งโปรแกรม SLAM Card Reader · ข้อมูลจะเติมในฟอร์มก่อนบันทึก</p><button type="button" className="secondary" disabled={disabled||waiting} onClick={connect}>{waiting?'กำลังรอข้อมูลบัตร…':'อ่านบัตรประชาชน / เสียบบัตร'}</button>{waiting&&<button type="button" className="textbtn" onClick={()=>{cleanup.current();setMessage('ยกเลิกการรอข้อมูล')}}>ยกเลิกการรอ</button>}{message&&<p role="status">{message}</p>}<details><summary>ตั้งค่าเครื่องอ่านครั้งแรก</summary><p>ดาวน์โหลดชุดเชื่อมต่อ แตก ZIP ติดตั้ง Python 3 และไดรเวอร์เครื่องอ่าน แล้วเปิด install-windows.cmd ครั้งแรก จากนั้นเปิด start-windows.cmd ค้างไว้บนคอมที่เสียบเครื่องอ่าน</p><a href="https://github.com/purongair-app/slamphone/tree/main/card-reader" target="_blank" rel="noopener noreferrer">ชุดโปรแกรมและคู่มือติดตั้ง</a></details></section>
}
