'use client';
import {useEffect,useRef,useState} from 'react';
export function repairImages(row:any):string[]{const sources=[...(Array.isArray(row?.photos)?row.photos:[]),row?.image,row?.photo];return [...new Set(sources.filter((v):v is string=>typeof v==='string'&&(/^data:image\/(jpeg|png|webp);base64,/.test(v)||/^https:\/\//.test(v))))]}
async function compress(file:File){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('เลือกไฟล์ JPG PNG หรือ WEBP');
 if(file.size>15*1024*1024)throw Error('เลือกรูปขนาดไม่เกิน 15 MB');
 const url=URL.createObjectURL(file),image=new Image();
 try{await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('อ่านรูปภาพไม่ได้'));image.src=url});const ratio=Math.min(1,1280/image.width,1280/image.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*ratio));canvas.height=Math.max(1,Math.round(image.height*ratio));canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);let data='';for(const quality of [.8,.6,.4]){data=canvas.toDataURL('image/jpeg',quality);if(data.length<=350000)return data}throw Error('รูปมีรายละเอียดมากเกินไป กรุณาเลือกรูปที่เล็กลง')}finally{URL.revokeObjectURL(url)}
}
export function ImageGallery({images}:{images:string[]}){return images.length?<div className="attachmentgrid">{images.map((src,i)=><a href={src} target="_blank" rel="noopener noreferrer" key={src} aria-label={'เปิดรูปแนบ '+(i+1)}><img src={src} alt={'รูปแนบ '+(i+1)}/></a>)}</div>:null}
export default function ImageAttachments({images,onChange,max=6,disabled=false,onPreparing}:{images:string[];onChange:(images:string[])=>void;max?:number;disabled?:boolean;onPreparing?:(preparing:boolean)=>void}){
 const [loading,setLoading]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null),active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;onPreparing?.(false)}},[onPreparing]);
 return <div className="attachments wide"><h3>{max===1?'รูปสินค้า':'แนบรูปเครื่อง / อาการเสีย'}</h3><p className="hint">เลือกจากคลังรูปหรือถ่ายภาพด้วยมือถือ · JPG PNG WEBP · {max===1?'1 รูป':'สูงสุด '+max+' รูป'} · รูปจะบันทึกพร้อมข้อมูลรายการ</p><label className="secondary uploadbutton">{loading?'กำลังเตรียมรูป…':max===1?'เลือกรูปสินค้า':'เพิ่มรูปแนบ'}<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" multiple={max>1} disabled={disabled||loading||images.length>=max} onChange={async e=>{const files=Array.from(e.target.files??[]);e.target.value='';setError('');if(files.length+images.length>max){setError('แนบได้สูงสุด '+max+' รูป');return}setLoading(true);onPreparing?.(true);try{const added=[];for(const file of files)added.push(await compress(file));if(active.current)onChange([...images,...added])}catch(e){if(active.current)setError((e as Error).message)}finally{if(active.current){setLoading(false);onPreparing?.(false)}}}}/></label><div className="attachmentgrid">{images.map((src,i)=><div key={src}><a href={src} target="_blank" rel="noopener noreferrer"><img src={src} alt={'รูปแนบ '+(i+1)}/></a><button type="button" className="textbtn" disabled={disabled||loading} onClick={()=>onChange(images.filter((_,index)=>index!==i))}>นำรูปที่ {i+1} ออก</button></div>)}</div>{error&&<p className="formerror" role="alert">{error}</p>}</div>
}
