'use client';
import {useState} from 'react';import {Store,Row,uid,money,day} from '@/lib/store';import {mergePrices} from '@/lib/business';import {Plus,Upload,Download,Search,Settings2,X,Trash2,Check} from 'lucide-react';
const brands=['Apple · iPhone','Apple · iPad','Huawei','Infinix','OPPO','Realme','Redmi','Samsung','Tecno','Vivo','Wiko','Xiaomi'];const jobs=['เปลี่ยนจอ','เปลี่ยนแบตเตอรี่','เปลี่ยนพอร์ตชาร์จ','เปลี่ยนฝาหลัง','เปลี่ยนกล้อง','ซ่อมบอร์ด'];const grades=['TFT','แท้','แท้ลอก','OLED','AAA/TFT','มาตรฐาน'];
const blank=()=>({id:uid(),brand:brands[0],model:'',work:jobs[0],grade:'มาตรฐาน',warranty:'30 วัน',cost:0,price:0,date:day()});
export default function PriceBook({s,commit,busy,onUse,editable=true}:{s:Store;commit:(n:Store)=>Promise<boolean>;busy:boolean;onUse:(r:Row)=>void;editable?:boolean}){
 const [search,setSearch]=useState(''),[brand,setBrand]=useState('ทั้งหมด'),[work,setWork]=useState('ทั้งหมด'),[view,setView]=useState('list'),[display,setDisplay]=useState('price'),[editor,setEditor]=useState<Row[]|null>(null),[tools,setTools]=useState(false),[error,setError]=useState(''),[markup,setMarkup]=useState(50),[warranty,setWarranty]=useState('30 วัน'),[importRows,setImportRows]=useState<Row[]|null>(null);
 const rows=s.prices.filter(r=>(brand==='ทั้งหมด'||r.brand===brand)&&(work==='ทั้งหมด'||r.work===work)&&JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));const brandOptions=Array.from(new Set([...brands,...s.prices.map(r=>r.brand)]));const workOptions=Array.from(new Set([...jobs,...s.prices.map(r=>r.work)]));const models=Array.from(new Set(rows.map(r=>r.model)));const gradeOptions=Array.from(new Set([...grades,...rows.map(r=>r.grade)]));
 async function workbook(rows:any[],name:string){const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'ราคาซ่อม');XLSX.writeFile(wb,name+'.xlsx');}
 const exportRows=(r:Row[])=>r.map(x=>({'ยี่ห้อ':x.brand,'รุ่น':x.model,'งานซ่อม':x.work,'เกรด':x.grade,'ประกัน':x.warranty,'ต้นทุน':x.cost,'ราคาซ่อม':x.price}));
 async function readFile(file:File){try{if(file.size>5*1024*1024)throw Error('ไฟล์ต้องไม่เกิน 5 MB');const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer());const raw=XLSX.utils.sheet_to_json<Record<string,any>>(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!raw.length||raw.length>3000)throw Error('ไฟล์ต้องมี 1–3,000 แถว');const incoming=raw.map(r=>({...blank(),brand:String(r['ยี่ห้อ']??r.brand??'').trim(),model:String(r['รุ่น']??r.model??'').trim(),work:String(r['งานซ่อม']??r.work??'').trim(),grade:String(r['เกรด']??r.grade??'มาตรฐาน'),warranty:String(r['ประกัน']??r.warranty??'30 วัน'),cost:Number(String(r['ต้นทุน']??r.cost??0).replaceAll(',','')),price:Number(String(r['ราคาซ่อม']??r.price??'').replaceAll(',',''))}));if(raw.some(r=>String(r['ราคาซ่อม']??r.price??'').trim()===''))throw Error('กรอกราคาซ่อมให้ครบก่อนนำเข้า');mergePrices(s.prices,incoming);setImportRows(incoming);setError('');}catch(e){setError((e as Error).message)}}
 async function saveRows(){if(!editor)return;try{const next=structuredClone(s);next.prices=mergePrices(s.prices,editor);if(await commit(next)){setEditor(null);setError('')}}catch(e){setError((e as Error).message)}}
 function editRows(r:Row[]){setEditor(r.map(x=>({...x})));setError('')}
 async function del(r:Row){if(!confirm('ลบราคาของ '+r.model+' '+r.work+' '+r.grade+' ?'))return;const n=structuredClone(s);n.prices=n.prices.filter(x=>x.id!==r.id);await commit(n)}
 return <section className="card pricebook"><div className="cardtitle"><div><h2>ตารางราคาซ่อม</h2><p>ต้นทุน ราคาซ่อม และประกัน แยกตามรุ่นและเกรดอะไหล่</p></div><span className="badge">{rows.length} รายการ</span></div><div className="toolbar">{editable&&<><button className="primary" onClick={()=>editRows([blank()])}><Plus size={16}/> เพิ่มราคา</button><label className="secondary uploadbutton"><Upload size={16}/> นำเข้าราคา<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)readFile(f);e.target.value=''}}/></label><button className="secondary" onClick={()=>setTools(!tools)}><Settings2 size={16}/> เครื่องมือ</button></>}<button className="secondary" onClick={()=>workbook(exportRows(rows),'ราคาซ่อม-'+day())}><Download size={16}/> ส่งออก Excel</button></div>{error&&<div className="alert" role="alert">{error}</div>}
 {tools&&<div className="pricetools"><div className="formgrid"><label>บวกจากต้นทุน (%)<input type="number" min="0" value={markup} onChange={e=>setMarkup(Number(e.target.value))}/></label><label>ประกันเริ่มต้น<input value={warranty} onChange={e=>setWarranty(e.target.value)}/></label></div><div className="toolbar"><button className="secondary" disabled={!rows.length||!Number.isFinite(markup)||markup<0} onClick={()=>editRows(rows.map(r=>({...r,price:Math.round(r.cost*(1+markup/100)*100)/100})))}>ตั้งราคาจากต้นทุน · ดูก่อนบันทึก</button><button className="secondary" disabled={!rows.length} onClick={()=>editRows(rows.map(r=>({...r,warranty})))}>ตั้งประกันหลายรายการ</button><button className="secondary" onClick={()=>workbook([{'ยี่ห้อ':brands[0],'รุ่น':'กรอกรุ่น','งานซ่อม':jobs[0],'เกรด':'OLED','ประกัน':'30 วัน','ต้นทุน':'','ราคาซ่อม':''}],'แบบฟอร์มนำเข้าราคา')}>ดาวน์โหลดแบบฟอร์ม</button></div></div>}
 <label className="search"><Search size={18}/><input placeholder="ค้นหารุ่น งานซ่อม หรือเกรด เช่น iPhone 13 OLED" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="pricefilters"><select aria-label="กรองยี่ห้อ" value={brand} onChange={e=>setBrand(e.target.value)}><option value="ทั้งหมด">ทุกยี่ห้อ</option>{brandOptions.map(x=><option key={x}>{x}</option>)}</select><select aria-label="กรองงานซ่อม" value={work} onChange={e=>setWork(e.target.value)}><option value="ทั้งหมด">ทุกงานซ่อม</option>{workOptions.map(x=><option key={x}>{x}</option>)}</select><div className="segmented"><button className={view==='list'?'selected':''} onClick={()=>setView('list')}>แบบรายการ</button><button className={view==='matrix'?'selected':''} onClick={()=>setView('matrix')}>แบบตาราง</button></div></div>
 {view==='list'?<div className="tablewrap"><table><thead><tr>{['ยี่ห้อ / รุ่น','งานซ่อม / อะไหล่','เกรด','ประกัน',...(editable?['ต้นทุน']:[]),'ราคาซ่อม',...(editable?['ส่วนต่าง']:[]),'จัดการ'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.model}</b><small className="block">{r.brand}</small></td><td>{r.work}</td><td><span className="badge">{r.grade}</span></td><td>{r.warranty}</td>{editable&&<td>{money(r.cost)}</td>}<td><b>{money(r.price)}</b></td>{editable&&<td>{money(r.price-r.cost)}</td>}<td><div className="rowactions"><button className="textbtn" onClick={()=>onUse(r)}>ใช้รับงาน</button>{editable&&<><button className="textbtn" onClick={()=>editRows([r])}>แก้ไข</button><button className="iconbtn" aria-label="ลบราคา" onClick={()=>del(r)}><Trash2 size={15}/></button></>}</div></td></tr>)}</tbody></table></div>:<><div className="matrixhead"><div><h3>{brand==='ทั้งหมด'?'ทุกยี่ห้อ':brand}</h3><p>{work==='ทั้งหมด'?'ทุกงานซ่อม':work} · {models.length} รุ่น</p></div><div className="toolbar"><div className="segmented">{(editable?['cost','price','warranty']:['price','warranty']).map(k=><button key={k} className={display===k?'selected':''} onClick={()=>setDisplay(k)}>{({cost:'ต้นทุน',price:'ราคาซ่อม',warranty:'ประกัน'} as any)[k]}</button>)}</div>{editable&&<button className="primary" disabled={!rows.length} onClick={()=>editRows(rows)}>แก้ไขตาราง</button>}</div></div><div className="tablewrap matrix"><table><thead><tr><th>รุ่น / งาน</th>{gradeOptions.map(g=><th key={g}>{g}</th>)}</tr></thead><tbody>{Array.from(new Set(rows.map(r=>r.brand+'|'+r.model+'|'+r.work))).map(key=>{const [b,m,w]=key.split('|');return <tr key={key}><th>{m}<small className="block">{b} · {w}</small></th>{gradeOptions.map(g=>{const r=rows.find(x=>x.brand===b&&x.model===m&&x.work===w&&x.grade===g);return <td key={g}>{r?<button className="cellprice" onClick={()=>editable?editRows([r]):onUse(r)}>{display==='warranty'?r.warranty:money(r[display])}</button>:'—'}</td>})}</tr>})}</tbody></table></div></>}
 {!rows.length&&<div className="empty"><h3>เริ่มสร้างรายการงานและราคาของร้าน</h3><p>เพิ่มรายการแรก หรือนำเข้าราคาจากไฟล์ Excel / CSV ของคุณ</p></div>}
 {editor&&<div className="modalback"><section className="modal priceeditor" role="dialog" aria-modal="true" aria-label="แก้ไขราคาซ่อม"><div className="modalhead"><div><small>แก้ไขหลายแถว · บันทึกพร้อมกัน</small><h2>ราคาซ่อมและต้นทุน</h2></div><button className="iconbtn" aria-label="ปิดตารางราคา" onClick={()=>setEditor(null)}><X/></button></div><div className="tablewrap editprice"><table><thead><tr>{['ยี่ห้อ','รุ่น','งานซ่อม','เกรด','ต้นทุน','ราคาซ่อม','ประกัน'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{editor.map((r,i)=><tr key={r.id}>{['brand','model','work','grade','cost','price','warranty'].map(k=><td key={k}><input aria-label={k+' แถว '+(i+1)} type={['price','cost'].includes(k)?'number':'text'} min="0" step="any" list={k==='brand'?'pricebrands':k==='work'?'pricejobs':k==='grade'?'pricegrades':undefined} value={r[k]} onChange={e=>setEditor(editor.map((x,j)=>j===i?{...x,[k]:['price','cost'].includes(k)?Number(e.target.value):e.target.value}:x))}/></td>)}</tr>)}</tbody></table><datalist id="pricebrands">{brands.map(x=><option key={x}>{x}</option>)}</datalist><datalist id="pricejobs">{jobs.map(x=><option key={x}>{x}</option>)}</datalist><datalist id="pricegrades">{grades.map(x=><option key={x}>{x}</option>)}</datalist></div>{error&&<p className="formerror">{error}</p>}<div className="modalfoot"><button className="secondary" onClick={()=>setEditor([...editor,blank()])}><Plus size={16}/> เพิ่มแถว</button><button className="primary" disabled={busy} onClick={saveRows}><Check size={16}/> บันทึก {editor.length} แถว</button></div></section></div>}
 {importRows&&<div className="modalback"><section className="modal"><div className="modalhead"><h2>ตรวจสอบก่อนนำเข้า {importRows.length} รายการ</h2><button className="iconbtn" aria-label="ปิดนำเข้า" onClick={()=>setImportRows(null)}><X/></button></div><div className="detailbody"><p>แถวที่ยี่ห้อ รุ่น งาน และเกรดตรงกันจะอัปเดตราคา แถวอื่นจะเพิ่มเป็นรายการใหม่</p><div className="tablewrap"><table><thead><tr><th>รุ่น</th><th>งาน</th><th>เกรด</th><th>ต้นทุน</th><th>ราคา</th></tr></thead><tbody>{importRows.slice(0,20).map((r,i)=><tr key={i}><td>{r.brand} {r.model}</td><td>{r.work}</td><td>{r.grade}</td><td>{money(r.cost)}</td><td>{money(r.price)}</td></tr>)}</tbody></table></div><p className="hint">ตัวอย่างสูงสุด 20 แถว · รวม {importRows.length} แถว</p></div><div className="modalfoot"><button className="secondary" onClick={()=>setImportRows(null)}>ยกเลิก</button><button className="primary" disabled={busy} onClick={async()=>{const n=structuredClone(s);n.prices=mergePrices(s.prices,importRows);if(await commit(n))setImportRows(null)}}>ยืนยันนำเข้า</button></div></section></div>}
 </section>
}
