'use client';
import {useState} from 'react';
import {Printer, Eye} from 'lucide-react';
import {paperOptions} from '@/lib/printing';
type Props = {settings:Record<string,any>;onChange:(key:string,value:any)=>void;onPreview:(kind?:string)=>void};
export default function PrinterSettings({settings:d,onChange:set,onPreview}:Props){
 const [device,setDevice]=useState(()=>{try{return JSON.parse(localStorage.getItem('mobilehub-printer-v1')||'{}')}catch{return {}}});
 const [message,setMessage]=useState('');
 function remember(){try{localStorage.setItem('mobilehub-printer-v1',JSON.stringify(device));setMessage('บันทึกข้อมูลเครื่องนี้แล้ว เลือกเครื่องพิมพ์จริงในหน้าพิมพ์อีกครั้ง')}catch{setMessage('เบราว์เซอร์ไม่อนุญาตให้จำข้อมูลเครื่องพิมพ์ กรุณาเลือกในหน้าพิมพ์')}}
 return <><section className="card"><h2><Printer size={20}/> เชื่อมต่อเครื่องพิมพ์</h2><p>ใช้เครื่องพิมพ์ที่ติดตั้งหรือจับคู่กับมือถือ แท็บเล็ต หรือคอมพิวเตอร์นี้ ผ่านหน้าพิมพ์ของเบราว์เซอร์</p><div className="formgrid innerform"><label>ชื่อ / รุ่นเครื่องพิมพ์ในเครื่องนี้<input maxLength={100} placeholder="เช่น เครื่องพิมพ์ใบเสร็จหน้าร้าน" value={device.name||''} onChange={e=>setDevice({...device,name:e.target.value})}/></label><label>การเชื่อมต่อกับอุปกรณ์<select value={device.connection||'usb'} onChange={e=>setDevice({...device,connection:e.target.value})}><option value="usb">USB</option><option value="bluetooth">Bluetooth</option><option value="network">Wi-Fi / LAN</option><option value="pdf">บันทึก PDF</option></select></label></div><div className="toolbar"><button type="button" className="secondary" onClick={remember}>จำข้อมูลเครื่องพิมพ์บนอุปกรณ์นี้</button><button type="button" className="primary" onClick={()=>onPreview('ตัวอย่างทดสอบเครื่องพิมพ์')}><Printer size={16}/> เลือกเครื่องพิมพ์ / ทดสอบ</button></div>{message&&<p role="status">{message}</p>}<p className="hint">ชื่อและวิธีเชื่อมต่อเป็นข้อมูลช่วยจำ ระบบไม่ได้ตรวจว่าเครื่องออนไลน์ เปิดตัวอย่างแล้วกด “พิมพ์ / PDF” เพื่อเลือกเครื่องและสั่งพิมพ์จริง</p><details><summary>วิธีเชื่อมต่อและแก้ปัญหาเครื่องพิมพ์ไม่แสดง</summary><ol><li>USB: ต่อสายและติดตั้งไดรเวอร์ของผู้ผลิตบนคอมพิวเตอร์ก่อน</li><li>Wi-Fi / LAN: ให้เครื่องพิมพ์และอุปกรณ์อยู่ในเครือข่ายเดียวกัน และเพิ่มเครื่องในระบบปฏิบัติการ</li><li>Bluetooth: จับคู่ในตั้งค่าของอุปกรณ์ และใช้บริการพิมพ์ที่รองรับรุ่นนั้น</li><li>เปิดผ่าน Chrome หรือ Safari โดยตรง เลือกเครื่อง ขนาดกระดาษที่ตรงกัน สเกล 100% และปิดหัว/ท้ายกระดาษของเบราว์เซอร์</li></ol></details></section>
 <section className="card"><h2>ตั้งค่าหน้ากระดาษ</h2><p>ใช้กับการพิมพ์เอกสาร ทั้งรายการใหม่และเอกสารย้อนหลัง</p><div className="formgrid innerform"><label>กระดาษใบเสร็จ<select value={d.receiptPaper||'80mm'} onChange={e=>set('receiptPaper',e.target.value)}>{paperOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>กระดาษใบรับซ่อม<select value={d.jobPaper||'80mm'} onChange={e=>set('jobPaper',e.target.value)}>{paperOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>แนวกระดาษ A4 / A5<select value={d.printOrientation||'portrait'} onChange={e=>set('printOrientation',e.target.value)}><option value="portrait">แนวตั้ง</option><option value="landscape">แนวนอน</option></select></label><label>ระยะขอบทุกด้าน (มม.)<input type="number" min={0} max={8} step={0.5} required value={d.printMargin??3} onChange={e=>set('printMargin',e.target.value===''?'':Number(e.target.value))}/></label><label>ขนาดตัวอักษรเอกสาร (px)<input type="number" min={9} max={18} step={1} required value={d.printFontSize??11} onChange={e=>set('printFontSize',e.target.value===''?'':Number(e.target.value))}/></label><label>ความยาวหน้ากระดาษม้วน 58 / 80 มม.<input type="number" min={60} max={500} step={1} required value={d.printRollHeight??200} onChange={e=>set('printRollHeight',e.target.value===''?'':Number(e.target.value))}/></label></div><p className="hint">กระดาษม้วนใช้ความยาวหน้าตามที่กำหนด เลือกขนาดเดียวกันในไดรเวอร์เครื่องพิมพ์ด้วย เอกสารยาวจะแบ่งหลายหน้า</p><div className="toolbar"><button type="button" className="secondary" onClick={()=>onPreview('ตัวอย่างใบเสร็จ')}><Eye size={16}/> ตัวอย่างใบเสร็จ</button><button type="button" className="secondary" onClick={()=>onPreview('ใบรับซ่อม (ทดสอบ)')}><Eye size={16}/> ตัวอย่างใบรับซ่อม</button></div><p className="hint">ตัวอย่างใช้ค่าที่กำลังปรับ กดบันทึกการตั้งค่าเครื่องพิมพ์เพื่อใช้กับเอกสารอื่น</p></section></>;
}
