'use client';
import PhoneInput from './PhoneInput';
import {formatPhone,validPhone} from '@/lib/phone';
import {useEffect,useState} from 'react';import {Store,Row} from '@/lib/store';import {defaultSettings} from '@/lib/business';import {Store as ShopIcon,Receipt,Wallet,MessageCircle,Save,Upload,Download,Eye,Trash2} from 'lucide-react';
export default function SettingsPanel({s,commit,busy,onPreview,onBackup,onReset}:{s:Store;commit:(n:Store)=>Promise<boolean>;busy:boolean;onPreview:()=>void;onBackup:()=>void;onReset:()=>void}){
 const [tab,setTab]=useState('shop'),[d,setD]=useState({...defaultSettings,...s.settings}),[err,setErr]=useState(''),[connected,setConnected]=useState(false);
 useEffect(()=>{fetch('/api/integrations').then(r=>r.json()).then((v:any)=>setConnected(!!v.lineConfigured)).catch(()=>setConnected(false))},[]);
 const set=(k:string,v:any)=>setD(x=>({...x,[k]:v}));
 const text=(key:string,label:string,type='text',wide=false)=><label className={wide?'wide':''}>{label}{key==='phone'?<PhoneInput value={(d as any)[key]??''} onChange={value=>set(key,value)}/>:type==='textarea'?<textarea value={(d as any)[key]??''} onChange={e=>set(key,e.target.value)}/>:<input type={type} value={(d as any)[key]??''} onChange={e=>set(key,e.target.value)}/>}</label>;
 async function save(e?:React.FormEvent){e?.preventDefault();if(!d.name.trim()){setErr('กรุณากรอกชื่อร้าน');return}if(!validPhone(d.phone)){setErr('กรุณากรอกเบอร์โทรให้ครบ 10 หลัก');return}if(d.promptpay&&!/^(\d{10}|\d{13})$/.test(d.promptpay.replace(/\D/g,''))){setErr('พร้อมเพย์ต้องเป็นเบอร์โทร 10 หลักหรือเลขประจำตัว 13 หลัก');return}if(d.lineOaUrl&&!/^https:\/\//.test(d.lineOaUrl)){setErr('ลิงก์ LINE ต้องขึ้นต้นด้วย https://');return}const n=structuredClone(s);n.settings={...n.settings,...d,phone:formatPhone(d.phone)};if(await commit(n))setErr('')}
 async function imageUpload(file:File,key:string){try{if(file.size>2*1024*1024)throw Error('รูปต้องไม่เกิน 2 MB');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('รองรับ JPEG, PNG และ WebP');const img=new Image();const url=URL.createObjectURL(file);try{await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(Error('อ่านรูปไม่ได้'));img.src=url});const scale=Math.min(1,600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');const n=structuredClone(s);n.settings={...n.settings,[key]:data};if(await commit(n))set(key,data)}finally{URL.revokeObjectURL(url)}}catch(e){setErr((e as Error).message)}}
 const upload=(key:string,label:string)=><div className="assetsetting"><h3>{label}</h3><div className="assetrow"><div className={'assetpreview '+(key==='signature'?'signature':'')}>{(d as any)[key]?<img src={(d as any)[key]} alt={label}/>:<span>ยังไม่มี{label}</span>}</div><div><label className="secondary uploadbutton"><Upload size={17}/> อัปโหลด{label}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)imageUpload(f,key);e.target.value=''}}/></label><p className="hint">JPEG, PNG, WebP ไม่เกิน 2 MB · อัปโหลดแล้วบันทึกทันที</p>{(d as any)[key]&&<button type="button" className="textbtn" onClick={async()=>{const n=structuredClone(s);n.settings[key]='';if(await commit(n))set(key,'')}}><Trash2 size={14}/> ลบรูป</button>}</div></div></div>;
 return <div className="settingspanel"><div className="settingtabs">{[['shop','ข้อมูลร้าน',ShopIcon],['receipt','ใบเสร็จและโลโก้',Receipt],['payment','การชำระเงิน',Wallet],['line','แจ้งเตือน LINE',MessageCircle]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</div><form onSubmit={save}>
 {tab==='shop'&&<><section className="card"><h2>ข้อมูลร้าน</h2><p>ข้อมูลที่ปรากฏบนใบรับซ่อมและใบเสร็จ</p><div className="formgrid innerform">{text('name','ชื่อร้าน / ชื่อกิจการ','text',true)}{text('phone','เบอร์โทรศัพท์')}{text('lineId','LINE ID')}{text('address','ที่อยู่','textarea',true)}{text('taxId','เลขประจำตัวผู้เสียภาษี')}{text('branch','สาขา')}</div></section><section className="card"><h2>ภาษีมูลค่าเพิ่ม (VAT 7%)</h2><p>ใช้กับบิลใหม่ บิลที่บันทึกแล้วคงยอดเดิม</p><div className="radiostack">{[['none','ไม่ได้จด VAT','ใบเสร็จไม่แสดง VAT'],['included','ราคารวม VAT แล้ว','แยกยอดภาษีที่รวมอยู่ในราคา'],['excluded','ราคายังไม่รวม VAT','บวก VAT 7% ในยอดชำระ']].map(([v,l,desc])=><label key={v} className={d.vatMode===v?'radiocard selected':'radiocard'}><input type="radio" name="vat" value={v} checked={d.vatMode===v} onChange={()=>set('vatMode',v)}/><span>{l}<small>{desc}</small></span></label>)}</div></section><section className="card"><h2>ฟีเจอร์ที่ใช้</h2><Toggle label="ลงเวลาเข้างาน–ออกงาน" description="ทะเบียนเวลาเข้าทำงานของพนักงาน · เปิดแล้วแสดงเมนู" value={d.enableAttendance} onChange={v=>set('enableAttendance',v)}/><Toggle label="เงินเดือนและค่าคอม" description="บันทึกเงินเดือน ค่าคอม และออกสลิป · เปิดแล้วแสดงเมนู" value={d.enablePayroll} onChange={v=>set('enablePayroll',v)}/><p className="hint">สาขาในเวอร์ชันนี้เป็นข้อมูลบนเอกสาร ยังไม่ได้แยกสต๊อกและสิทธิ์การเข้าถึงหลายสาขา</p></section><section className="card"><h2>ต้นทุนงานซ่อม</h2><Toggle label="แสดงต้นทุนในแบบฟอร์มรับงาน" value={d.showCosts} onChange={v=>set('showCosts',v)}/><label>ค่าอะไหล่งานซ่อมหักจาก<select value={d.costSource} onChange={e=>set('costSource',e.target.value)}><option value="job">ต้นทุนในใบงานซ่อม</option><option value="expense">บิลรายจ่ายที่บันทึกเอง</option></select></label><p className="hint">เลือกบิลรายจ่ายแล้วระบบจะไม่สร้างรายจ่ายต้นทุนซ้ำตอนปิดงาน</p></section></>}
 {tab==='receipt'&&<><section className="card"><h2>โลโก้และลายเซ็น</h2>{upload('logo','โลโก้ร้าน')}<Toggle label="แสดงโลโก้บนเอกสาร" value={d.showLogo} onChange={v=>set('showLogo',v)}/><label>ขนาดโลโก้<select value={d.logoSize} onChange={e=>set('logoSize',e.target.value)}><option value="small">เล็ก</option><option value="medium">กลาง</option><option value="large">ใหญ่</option><option value="xlarge">ใหญ่มาก</option></select></label><hr/>{upload('signature','ลายเซ็นร้าน')}<p className="hint">ลายเซ็นร้านแสดงบน A4/A5 ลูกค้ายังลงชื่อบนกระดาษได้</p></section><section className="card"><h2>รูปแบบใบเสร็จ</h2><div className="formgrid innerform"><label>กระดาษใบเสร็จ<select value={d.receiptPaper} onChange={e=>set('receiptPaper',e.target.value)}>{['58mm','80mm','A4','A5'].map(x=><option key={x}>{x}</option>)}</select></label><label>กระดาษใบรับซ่อม<select value={d.jobPaper} onChange={e=>set('jobPaper',e.target.value)}>{['58mm','80mm','A4','A5'].map(x=><option key={x}>{x}</option>)}</select></label>{text('footer','ข้อความท้ายใบเสร็จ','textarea',true)}{text('warranty','เงื่อนไขการรับประกัน','textarea',true)}{text('defaultWarranty','ระยะเวลารับประกันเริ่มต้น')}</div><Toggle label="เปิดหน้าพิมพ์หลังรับชำระ" description="เปิดเอกสารก่อน ต้องยืนยันพิมพ์ผ่านเบราว์เซอร์" value={d.autoPrint} onChange={v=>set('autoPrint',v)}/><button type="button" className="secondary" onClick={onPreview}><Eye size={16}/> ดูตัวอย่างที่บันทึกแล้ว</button><p className="hint">QR ติดตามงานสำหรับลูกค้าภายนอกยังไม่เปิดใช้ เพราะเว็บไซต์นี้เป็นพื้นที่ส่วนตัว</p></section></>}
 {tab==='payment'&&<section className="card"><h2>ข้อมูลการชำระเงิน</h2><p>แสดงในเอกสารและสร้าง QR พร้อมเพย์เมื่อเลือกโอนเงิน</p><Toggle label="แสดง QR พร้อมเพย์เมื่อเลือกโอน" value={d.showPaymentQr} onChange={v=>set('showPaymentQr',v)}/><div className="formgrid innerform">{text('bank','ธนาคาร')}{text('accountNo','เลขบัญชี')}{text('accountName','ชื่อบัญชี')}{text('promptpay','พร้อมเพย์ (เบอร์โทร / เลขประจำตัว)')}{text('paymentNote','หมายเหตุการชำระเงิน','textarea',true)}</div><p className="hint">QR ช่วยกรอกยอดเงิน ไม่ได้ตรวจสอบเงินเข้าบัญชีอัตโนมัติ</p></section>}
 {tab==='line'&&<><section className="card"><h2><MessageCircle size={20}/> LINE ของร้าน</h2><p>เก็บลิงก์ LINE OA เพื่อให้เปิดแชตและส่งข้อความหาลูกค้าด้วยตนเอง</p><div className="formgrid innerform">{text('lineId','LINE ID ของร้าน')}{text('lineOaUrl','ลิงก์ LINE OA (https://lin.ee/…)')}</div>{d.lineOaUrl&&/^https:\/\//.test(d.lineOaUrl)&&<a className="secondary" href={d.lineOaUrl} target="_blank" rel="noreferrer">เปิด LINE ร้าน</a>}</section><section className="card"><h2>การแจ้งเตือนอัตโนมัติ</h2><span className={'badge '+(connected?'green':'')}>{connected?'มีข้อมูลเชื่อมต่อในเซิร์ฟเวอร์':'ยังไม่ได้เชื่อมต่อ'}</span><p className="hint">ต้องตั้งค่า Channel Access Token และ User ID / Group ID ในเซิร์ฟเวอร์ก่อน ระบบจะไม่แสดงหรือบันทึก Token ในหน้าร้านหรือไฟล์สำรอง</p><p className="hint">เวอร์ชันนี้ยังไม่ส่งข้อความ LINE อัตโนมัติ และยังไม่รองรับการยืนยันลูกค้าผ่าน QR</p></section></>}
 {err&&<div className="alert" role="alert">{err}</div>}<div className="settingssave"><span>บันทึกการตั้งค่า · บิลใหม่ใช้ค่าที่บันทึกแล้ว</span><button className="primary" disabled={busy}><Save size={18}/> บันทึก{tab==='shop'?'ข้อมูลร้าน':tab==='receipt'?'รูปแบบใบเสร็จ':tab==='payment'?'ข้อมูลการชำระเงิน':'ข้อมูล LINE'}</button></div></form><section className="card backupcard"><h2>สำรองข้อมูลร้าน</h2><p>เก็บข้อมูลร้านและรายการทั้งหมดเป็น JSON</p><button className="secondary" onClick={onBackup}><Download size={17}/> ดาวน์โหลดข้อมูลสำรอง</button></section><section className="card resetentry"><h2>รีเซ็ตระบบ / ตั้งค่าร้านใหม่</h2><p>ล้างข้อมูลธุรกิจทั้งหมดและคืนการตั้งค่าร้านเป็นค่าเริ่มต้น</p><button className="danger" onClick={onReset}>เปิดหน้ารีเซ็ตระบบ</button></section></div>
}
function Toggle({label,description,value,onChange}:{label:string;description?:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="togglerow"><div><b>{label}</b>{description&&<small>{description}</small>}</div><button type="button" role="switch" aria-checked={!!value} aria-label={label} className={'toggle '+(value?'on':'')} onClick={()=>onChange(!value)}><i/></button></div>}
